export const APRIL_30 = [
  { id: 1001, meal: "Breakfast", name: "Non-fat Greek yogurt (194g)",                         calories: 114, protein: 20,  carbs: 8,  fat: 0   },
  { id: 1002, meal: "Breakfast", name: "Strawberries (57g)",                                   calories: 18,  protein: 0.5, carbs: 4,  fat: 0   },
  { id: 1003, meal: "Breakfast", name: "Blueberries (57g)",                                    calories: 33,  protein: 1,   carbs: 8,  fat: 0   },
  { id: 1004, meal: "Breakfast", name: "Kirkland Ancient Grain Probiotic Granola (29g)",       calories: 132, protein: 3,   carbs: 18, fat: 5   },
  { id: 1005, meal: "Breakfast", name: "Kirkland Variety Pastry (1 piece)",                    calories: 200, protein: 3,   carbs: 24, fat: 10  },
  { id: 1006, meal: "Lunch",     name: "Hard boiled eggs (2 whole)",                           calories: 140, protein: 12,  carbs: 1,  fat: 10  },
  { id: 1007, meal: "Lunch",     name: "Boudin sourdough bread (1 slice/47g)",                 calories: 120, protein: 4,   carbs: 23, fat: 1   },
  { id: 1008, meal: "Lunch",     name: "Principe Prosciutto di San Daniele (4 slices/56g)",    calories: 136, protein: 16,  carbs: 0,  fat: 8   },
  { id: 1009, meal: "Lunch",     name: "Queso fresco (30g)",                                   calories: 96,  protein: 6,   carbs: 1,  fat: 8   },
  { id: 1010, meal: "Dinner",    name: "Chicken breast, cooked (weighed portion)",             calories: 100, protein: 14,  carbs: 0,  fat: 1   },
  { id: 10101,meal: "Dinner",    name: "Golden potatoes, diced (weighed portion)",             calories: 45,  protein: 1.2, carbs: 10, fat: 0   },
  { id: 1011, meal: "Dinner",    name: "Carrots, chopped (weighed portion)",                   calories: 17,  protein: 0.4, carbs: 4,  fat: 0   },
  { id: 10111,meal: "Dinner",    name: "Celery (weighed portion)",                             calories: 5,   protein: 0.2, carbs: 1,  fat: 0   },
  { id: 10112,meal: "Dinner",    name: "Yellow onion (weighed portion)",                       calories: 18,  protein: 0.5, carbs: 4,  fat: 0   },
  { id: 10113,meal: "Dinner",    name: "Roma tomato (weighed portion)",                        calories: 4,   protein: 0.2, carbs: 1,  fat: 0   },
  { id: 10114,meal: "Dinner",    name: "Olive oil ~1 tsp (soup portion)",                      calories: 13,  protein: 0,   carbs: 0,  fat: 1.5 },
  { id: 10115,meal: "Dinner",    name: "Knorr chicken stock + spices",                         calories: 13,  protein: 3.5, carbs: 1,  fat: 0   },
  { id: 10116,meal: "Dinner",    name: "Bowtie pasta, cooked (35g)",                           calories: 52,  protein: 2,   carbs: 11, fat: 0   },
  { id: 1012, meal: "Snack",     name: "Mission Carb Balance flour tortillas (2/86g)",         calories: 140, protein: 12,  carbs: 22, fat: 4   },
  { id: 1013, meal: "Snack",     name: "Kirkland Monterey Jack cheese (46g)",                  calories: 100, protein: 14,  carbs: 1,  fat: 8   },
  { id: 1014, meal: "Snack",     name: "Principe Prosciutto di San Daniele (4 slices/56g)",    calories: 136, protein: 16,  carbs: 0,  fat: 8   },
  { id: 1015, meal: "Snack",     name: "Banana (1 medium/105g)",                               calories: 105, protein: 1,   carbs: 27, fat: 0   },
  { id: 1016, meal: "Snack",     name: "ON Gold Standard Whey (1 scoop/31g)",                  calories: 120, protein: 24,  carbs: 4,  fat: 1.5 },
  { id: 1017, meal: "Snack",     name: "Kirkland 2% Lactose Free Milk (12oz/355ml)",           calories: 195, protein: 12,  carbs: 18, fat: 8   },
];

export const MAY_1 = [
  { id: 2001, meal: "Breakfast", name: "Whole eggs, cracked (4 eggs/~200g)",        calories: 280, protein: 24,  carbs: 2,  fat: 20  },
  { id: 2002, meal: "Breakfast", name: "Idaho Gold Potatoes (140g)",                calories: 104, protein: 2.8, carbs: 24, fat: 0   },
  { id: 2003, meal: "Breakfast", name: "Mission Carb Balance Tortilla (1/43g)",     calories: 70,  protein: 6,   carbs: 14, fat: 1   },
  { id: 2004, meal: "Breakfast", name: "Queso Fresco (17g)",                        calories: 55,  protein: 3.6, carbs: 0,  fat: 4   },
  { id: 2005, meal: "Breakfast", name: "Yellow onion (52g)",                        calories: 21,  protein: 0.6, carbs: 5,  fat: 0   },
  { id: 2006, meal: "Breakfast", name: "Roma tomato (99g)",                         calories: 18,  protein: 0.9, carbs: 4,  fat: 0   },
  { id: 2007, meal: "Breakfast", name: "Olive oil (1 tsp) + spices",               calories: 40,  protein: 0,   carbs: 0,  fat: 5   },
  { id: 2008, meal: "Breakfast", name: "Banana (1 medium)",                         calories: 105, protein: 1.3, carbs: 27, fat: 0   },
  { id: 2009, meal: "Breakfast", name: "Costco Pastry (1 piece)",                   calories: 155, protein: 3,   carbs: 22, fat: 6   },
  { id: 2010, meal: "Lunch",     name: "Non-fat Greek yogurt (206g)",               calories: 121, protein: 21.2,carbs: 8,  fat: 0   },
  { id: 2011, meal: "Lunch",     name: "Strawberries (58g)",                        calories: 19,  protein: 0.4, carbs: 5,  fat: 0   },
  { id: 2012, meal: "Lunch",     name: "Blueberries (69g)",                         calories: 39,  protein: 0.5, carbs: 10, fat: 0   },
  { id: 2013, meal: "Lunch",     name: "Kirkland Ancient Grain Granola (28g)",      calories: 128, protein: 2.9, carbs: 18, fat: 5   },
  { id: 2020, meal: "Dinner",    name: "Salmon fillet, pan seared (199g)",          calories: 372, protein: 44,  carbs: 0,  fat: 21  },
  { id: 2021, meal: "Dinner",    name: "Bell peppers (58g)",                        calories: 19,  protein: 0.6, carbs: 4,  fat: 0   },
  { id: 2022, meal: "Dinner",    name: "Cherry tomatoes (82g)",                     calories: 15,  protein: 0.7, carbs: 3,  fat: 0   },
  { id: 2023, meal: "Dinner",    name: "Carrots (118g)",                            calories: 41,  protein: 0.9, carbs: 10, fat: 0   },
  { id: 2024, meal: "Dinner",    name: "Celery (60g)",                              calories: 10,  protein: 0.4, carbs: 2,  fat: 0   },
  { id: 2025, meal: "Dinner",    name: "Corn (107g)",                               calories: 90,  protein: 3.4, carbs: 20, fat: 1   },
  { id: 2026, meal: "Dinner",    name: "Peas (50g)",                                calories: 42,  protein: 2.8, carbs: 7,  fat: 0   },
  { id: 2027, meal: "Dinner",    name: "Hellmann's Light Mayo (15g)",               calories: 45,  protein: 0,   carbs: 1,  fat: 4.5 },
  { id: 2028, meal: "Dinner",    name: "Vlasic Dill Pickles, 3 spears (28g)",       calories: 5,   protein: 0,   carbs: 1,  fat: 0   },
  { id: 2029, meal: "Dinner",    name: "Lemon juice + cilantro + spices",           calories: 5,   protein: 0.2, carbs: 1,  fat: 0   },
  { id: 2030, meal: "Snack",     name: "ON Gold Standard Whey (1 scoop/31g)",       calories: 120, protein: 24,  carbs: 4,  fat: 1.5 },
  { id: 2031, meal: "Snack",     name: "Kirkland 2% Lactose Free Milk (12oz/355ml)",calories: 195, protein: 12,  carbs: 18, fat: 8   },
];

export const MAY_2 = [
  { id: 4001, meal: "Breakfast", name: "Banana (1 medium)",                 calories: 105, protein: 1.3, carbs: 27, fat: 0  },
  { id: 4002, meal: "Breakfast", name: "Peanut butter (1 tbsp)",            calories: 94,  protein: 4,   carbs: 3,  fat: 8  },
  { id: 4003, meal: "Breakfast", name: "Boudin sourdough bread (1 slice)",   calories: 120, protein: 4,   carbs: 23, fat: 1  },
  { id: 4004, meal: "Lunch",     name: "3x3 Campus Burger (est.)",          calories: 1400,protein: 65,  carbs: 80, fat: 75 },
  { id: 4005, meal: "Lunch",     name: "Campus Fries (est.)",               calories: 450, protein: 6,   carbs: 58, fat: 22 },
];

export const MAY_3 = [
  { id: 3001, meal: "Breakfast", name: "Idaho Gold Potatoes (140g)",                    calories: 104, protein: 2.8, carbs: 24,   fat: 0   },
  { id: 3002, meal: "Breakfast", name: "Yellow onion (52g)",                            calories: 21,  protein: 0.6, carbs: 5,    fat: 0   },
  { id: 3003, meal: "Breakfast", name: "Roma tomato (99g)",                             calories: 18,  protein: 0.9, carbs: 4,    fat: 0   },
  { id: 3004, meal: "Breakfast", name: "Queso Fresco (17g)",                            calories: 55,  protein: 3.6, carbs: 0,    fat: 4   },
  { id: 3005, meal: "Breakfast", name: "Costco Pastry",                                 calories: 155, protein: 3,   carbs: 22,   fat: 6   },
  { id: 3006, meal: "Breakfast", name: "Orange",                                        calories: 62,  protein: 1,   carbs: 15,   fat: 0   },
  { id: 3007, meal: "Breakfast", name: "4 Scrambled Eggs",                              calories: 364, protein: 26,  carbs: 4,    fat: 28  },
  { id: 3008, meal: "Breakfast", name: "1 Medium Orange",                               calories: 62,  protein: 1.2, carbs: 15.4, fat: 0.2 },
  { id: 3009, meal: "Breakfast", name: "Kirkland 2% Lactose Free Milk (202ml)",         calories: 99,  protein: 6.6, carbs: 9.7,  fat: 3.9 },
  { id: 3010, meal: "Dinner",    name: "Turkey Sloppy Joes Mixer",                      calories: 290, protein: 18,  carbs: 38,   fat: 7   },
  { id: 3011, meal: "Dinner",    name: "Bun",                                           calories: 220, protein: 6,   carbs: 38,   fat: 4   },
  { id: 3012, meal: "Dinner",    name: "Costco Pastry",                                 calories: 155, protein: 3,   carbs: 20,   fat: 7   },
  { id: 3013, meal: "Dinner",    name: "Kirkland BellaVitano Cabernet Sauvignon Cheese (13g)", calories: 54, protein: 3, carbs: 0, fat: 5 },
  { id: 3014, meal: "Snack",     name: "Homemade Popcorn",                              calories: 300, protein: 9,   carbs: 51,   fat: 9   },
];

export const MAY_4 = [
  { id: 6007, meal: "Lunch",  name: "Turkey Sloppy Joe Meat Mix",                        calories: 210, protein: 22,   carbs: 18,  fat: 5   },
  { id: 6008, meal: "Lunch",  name: "Bun",                                               calories: 220, protein: 6,    carbs: 38,  fat: 5   },
  { id: 6009, meal: "Lunch",  name: "BellaVitano Cabernet Sauvignon Cheese (11g)",       calories: 43,  protein: 3,    carbs: 0,   fat: 3   },
  { id: 6010, meal: "Lunch",  name: "Ataulfo Mango (1 medium, ~150g)",                   calories: 95,  protein: 1,    carbs: 25,  fat: 0   },
  { id: 6001, meal: "Dinner", name: "Tri-color quinoa, cooked (half portion)",           calories: 170, protein: 6,    carbs: 30,  fat: 1.5 },
  { id: 6002, meal: "Dinner", name: "Carrots, chopped (~70g)",                           calories: 29,  protein: 0.7,  carbs: 7,   fat: 0   },
  { id: 6003, meal: "Dinner", name: "Celery (~50g)",                                     calories: 8,   protein: 0.3,  carbs: 1,   fat: 0   },
  { id: 6004, meal: "Dinner", name: "Peas (~50g)",                                       calories: 42,  protein: 2.8,  carbs: 7,   fat: 0   },
  { id: 6005, meal: "Dinner", name: "Mini bell pepper (~30g)",                           calories: 10,  protein: 0.4,  carbs: 2,   fat: 0   },
  { id: 6006, meal: "Dinner", name: "Kellogg's Club Crackers (15 crackers)",             calories: 263, protein: 1,    carbs: 34,  fat: 11  },
  { id: 6011, meal: "Dinner", name: "Cod 5oz with 1/2 tbsp butter",                     calories: 183, protein: 32,   carbs: 0,   fat: 6   },
  { id: 6012, meal: "Dinner", name: "1/6 cup frozen super sweet corn kernels",          calories: 22,  protein: 0.7,  carbs: 5.1, fat: 0.2 },
  { id: 6013, meal: "Snack",  name: "Multi Nut Mix",                                    calories: 170, protein: 5,    carbs: 8,   fat: 14  },
  { id: 6014, meal: "Snack",  name: "Plum (1 medium)",                                  calories: 30,  protein: 0.5,  carbs: 8,   fat: 0.2 },
  { id: 6015, meal: "Snack",  name: "Orange",                                           calories: 62,  protein: 1,    carbs: 15,  fat: 0   },
  { id: 6016, meal: "Snack",  name: "Banana + 2% Lactose Free Milk (14oz) + ON Gold Standard Whey", calories: 520, protein: 40, carbs: 57, fat: 10 },
];

export const MAY_5 = [
  { id: 7001, meal: "Breakfast", name: "Greek Yogurt with Strawberries and Blueberries",          calories: 284, protein: 26,   carbs: 28,  fat: 6   },
  { id: 7002, meal: "Breakfast", name: "Kirkland Signature Nature's Path Ancient Grains Granola", calories: 250, protein: 5,    carbs: 39,  fat: 9   },
  { id: 7003, meal: "Breakfast", name: "2% Milk (287ml)",                                         calories: 155, protein: 8,    carbs: 15,  fat: 6   },
  { id: 7004, meal: "Lunch",     name: "Turkey Sloppy Joes Mix (299g)",                           calories: 358, protein: 31,   carbs: 32,  fat: 11  },
  { id: 7005, meal: "Lunch",     name: "Bun",                                                     calories: 220, protein: 7,    carbs: 38,  fat: 4   },
  { id: 7006, meal: "Lunch",     name: "Cabernet Sauvignon BellaVitano (21g)",                    calories: 83,  protein: 5.25, carbs: 0.5, fat: 6.5 },
  { id: 7007, meal: "Dinner",    name: "12 oz Cod",                                               calories: 281, protein: 61,   carbs: 0,   fat: 2   },
  { id: 7008, meal: "Dinner",    name: "Tri-colored quinoa with mixed vegetables",                calories: 300, protein: 9,    carbs: 52,  fat: 4   },
  { id: 7009, meal: "Snack",     name: "Prosciutto di Parma (4 slices / 56g)",                    calories: 130, protein: 16,   carbs: 0,   fat: 8   },
];

export const MAY_1_WORKOUT = {
  id: 5001, date: "2026-05-01", dayIndex: 0,
  sessionNotes: "First session back. Landmine strategy — 44lb bar too heavy, landmine cuts load ~50%. Focus on mind-muscle connection.",
  logs: [
    { exId: "bike_warmup",        weight: 0,  sets: "1", reps: "15 min" },
    { exId: "landmine_goblet",    weight: 22, sets: "3", reps: "12"     },
    { exId: "landmine_rdl",       weight: 22, sets: "3", reps: "12"     },
    { exId: "split_squat",        weight: 0,  sets: "3", reps: "8 each" },
    { exId: "glute_bridge_floor", weight: 0,  sets: "3", reps: "20"     },
  ],
};
